### ISSUE TITLE
Mongoose Session config is hard coded to development connectionString

### ISSUE THREAD

**Issue by allain** [EthanRBrown/web-development-with-node-and-express#18]

**Comment by johnwargo** [comment]
There's no reason not to fix errors in the book's code here. Readers will understand (should) that when it's different here, it's because... you found a problem and fixed it here. Also, they'll be able to go back in history and see where the book's code diverged from the manuscript. I have absolutely no expectation that the repo is consistent with the book, my expectation is that this code is the best version of it.

**Comment by EthanRBrown** [comment]
@johnwargo, I've decided not to tell readers how they should or shouldn't use my book -- not only have I been embarrassed on occasion when readers turned out to be right, but who am I to presume the way another person should work?  Anyway, the new approach I think will work really well: readers who would prefer the repo match their version of the book exactly are satisfied, as well as people like yourself who want to see the latest changes (you can see them on master, and the next update branch).

**Comment by EthanRBrown** [comment]
@allain I have finally (!!!) gotten around to fixing this...thankfully I can do it much more easily with the new repo structure.  Since this does require a change to the book copy, the work has been done on the 1.5.1 branch.

**Comment by allain** [comment]
Sweet. Thanks.
