### ISSUE TITLE
Chapter 7 - Partials - Problem with express-handlebars

### ISSUE THREAD

**Issue by David-GER** [EthanRBrown/web-development-with-node-and-express#24]
When you install express3-handlebars - as the book suggests - npm gives you a deprecated warning because it was moved to express-handlebars. So I used express-handlebars until now because I seem to be reasonable to use the latest tools and I did not think that this would break anything. 

    npm WARN deprecated express3-handlebars@0.5.2: THIS PACKAGE HAS BEEN RENAMED TO: express-handlebars

At least until the following error occurred after I added the weather partial:

    Error
        at Object.<anonymous> ([...]Meadowlark/node_modules/express-handlebars/node_modules/handlebars/dist/cjs/handlebars/exception.js:29:23)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> ([...]Meadowlark/node_modules/express-handlebars/node_modules/handlebars/dist/cjs/handlebars/base.js:3:17)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)

After finding [this](http://stackoverflow.com/questions/29295898/express-and-handlebars-error-thrown-when-trying-to-render-object-passed-in-thro) StackOverflow post with the same Error code (but no solution) I found out, that it had something to do with the **res.locals.partials**

If I exchange **express-handlebars** with the deprecated **express3-handlebars** my code works fine. Also, when I update the [chapter8 solution](https://github.com/EthanRBrown/web-development-with-node-and-express/releases/tag/ch08) code to express-handlebars the same error occurs. 

Does anyone know why it does not work anymore? Maybe a workaround/different solution?

**Comment by trisager** [comment]
The weather partial in the sample code works with express-handlebars up through v.1.1.0.

express-handlebars v 1.2.0 introduces a "render-level partials feature" which breaks the sample code.

**Comment by zwb-ict** [comment]
@trisager Thank you, I meet this problem too.

**Comment by EthanRBrown** [comment]
Sorry to be chiming in so late, gentlemen.  Both of you are correct, and I am updating the book to reflect the changes to `express-handlebars`.  Fixing the sample code with newer versions of `express-handlebars` is a simple matter of changing the name of the context object that's passed to the partial.

**Comment by hujunyi** [comment]
the section helper doesn't work, either. Is this due to the same issue?

**Comment by smulder** [comment]
@EthanRBrown I am at a loss trying to follow your suggested correction could you please just point the line of code out we should change? I also am having a hard time finding the updated sample code here on Git that you referenced back in May on the O'reilly Errata page. Just a bit more guidance would be super helpful.

**Comment by smulder** [comment]
Thank you so much!

For anyone else, also change it in weather.handlebars

**Comment by EthanRBrown** [comment]
Hi, @smulter, sorry you're having issues seeing the updated sample code.  If you checkout master (`git checkout master`) and then pull the latest changes (`git pull`), you'll have the very latest (I just checked and found that the fix wasn't applied to all chapters; I just corrected that).

It's hard to answer your question about pointing out the exact line of code that needs to be changed without seeing your code...I'm just not sure where you're at.  The issue here is a feature added in `express-handlerbars` since the original publication of the book.

In the original publication, I was adding the weather context as `res.locals.partials.weather`.  `express-handlebars` now uses the `partials` namespace to allow you to override the partial template.  So specifying `res.locals.partials.weather` confuses it: it thinks you're trying to provide a new template, which is NOT the case.  So I simply changed the name of the property to `res.locals.partials.weatherContext` (alternatively I could have used `res.locals.partialContexts.weather`, which in retrospect might be a better idea).  Anyway, you need to change:

`res.locals.partials.<your partial name> = <your partial data>`

to

`res.locals.partials.<your partial name + Context> = <your partial data>`

And in the template, of course you'll need to change any references to `partials.<your partial name>` to `partials.<your partial name + Context>`.  I hope this makes sense!
