### ISSUE TITLE
Chapter 5: Mocha and Chai Global Tests

### ISSUE THREAD

**Issue by jkhan001** [EthanRBrown/web-development-with-node-and-express#3]
Up through chapter 5 I have been able to successfully run your examples. However, when I get into this chapter, I am finding many issues. First, to get the tests-global.js file to run I have to remove the if conditional statements. I am unable to apply ?test=1 to the query string and have it initiate the tests you have established so that we can hide the testing functionality. 

Second I placed this code in the home.handlebars file to get the test to run with the if conditionals removed. When I run this test on the home page, I do see the global test run on the browser with 0 passes and 1 failure.  However, I find an error with the assert statement also displayed in the browser: 
AssertionError: Unspecified AssertionError

I reviewed the documentation for chai assert statement (http://chaijs.com/api/assert/#assert) and find we should be using a form as follows: assert(expression, message) but your code is not written to this format. If you could please provide some clarification?

**Comment by clintconklin** [comment]
If anyone else runs into this, might be due to typing...

`var assert = chai.assert();`

...in main.handlebars, rather than...

`var assert = chai.assert;`

Or at least that's when I ran into this issue ;)

**Comment by EthanRBrown** [comment]
Thanks for the update, Javed!  I know these problems can be really frustrating, and I'm glad you got it worked out!

**Comment by Cryptolemming** [comment]
For anyone else running into issues with the initial ch05 tests - after much troubleshooting including rolling back dependency version etc - the solution for whatever reason lied in adding the following to main.handlebars:

<script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
	<script>window.jQuery || document.write('<script src="/vendor/js/jquery-2.1.1.min.js"><\/script>')</script>
	{{{_sections.jquery}}}

in between:

{{{body}}}
...paste here
{{#if showTests}}

Which is how it is structured in this repository.  Would be great to know why that helps.  Thanks.

*I was getting a 'mocha is not defined' error

**Comment by jamestrickey** [comment]
Hey - Sorry I know this thread is closed but @Cryptolemming - your work around worked for me too, and the hidden field is finally bing populated. Could anyone explain this to me?

Thanks!

**Comment by EthanRBrown** [comment]
Hi, @Cryptolemming and @jamestrickey, I am curious too as to why this is necessary.  My repository still works unmodified.  Without the fix, what do you see on the "network" tab in your browser?  Any 404s or 500s?  If one of y'all want to share your repo with me, I can take a look.

**Comment by jamestrickey** [comment]
Hey Ethan, thanks for getting back.

So the things I had to add were the following...

In main.js I had to add a helper to the handlebars creation or I got a 505 when navigating to the group rate page:

var handlebars = require('express-handlebars')
    .create({
        defaultLayout:'main',
        **helpers: {
            section: function(name, options){
                if(!this._sections) this._sections = {};
                this._sections[name] = options.fn(this);
                return null;
            }
        }**
    });

From what I've read online, this is apparently added later in the book but it seems to be needed for the page to parse at all.

Secondly, in main.handlebars I had to add Cryptolemming's suggestion of:

{{{body}}}
**{{{_sections.jquery}}}**
{{#if showTests}}

Not doing this results in the hidden input not being populated with the referrer.

Thanks

**Comment by jamestrickey** [comment]
Oh and sorry - i'm not working from a repo at the moment as travelling Australia in a van. Internet is hard to come by. :-)

**Comment by EthanRBrown** [comment]
Hi, @jamestrickey , thanks for the info.  I'm working on a 2nd edition of that book which is going to have _substantial_ changes, especially in the testing/QA chapter.

Seeing Australia in a van sounds amazing!  Best GitHub feedback ever!

**Comment by johnfdhartman** [comment]
I was getting this error for tests-about.js. After some debugging it seems the problem was that the `<a href='/contact>` in about.handlebars was appearing as `<a href='localhost:3000/contact'/>` in the browser, so `assert($('a[href="/contact"]').length)` was returning 0. Presumably this is due to a change in the handlebars transpiler?

In any case, I fixed it by running a slightly different test: 
```assert($('a').filter(function(){
			return this.href.match(/contact$/);
		}),length);
```
This searches for any `<a>` tag with an `href` pointing to something ending in `/contact`, and passes if there are more than one of them.

**Comment by ADAUS-joneill** [comment]
I've tried all of the solutions here but none of them are working for me, i'm still seeing the assertion errors.

**Comment by TUKenStone** [comment]
@ethanrbrown, you’d asked any 500s and I’ve got one when I navigate to https://localhost:3000/about or https://localhist:3000/about?test=1

I’m not sure I understand the difference between global tests and page-specific tests because it says both “500 - Server Error” and Global Tests” on /about?Test=1 but  “500 - Server Error” when on /about

**Comment by w3slley** [comment]
Hey everyone. I'm just getting an error while studing the chapter 5 of the book (a fantastic one so far, by the way). That's probably something I did somewhere because I changed a few things in the code (but stayed consistent with the examples in the book). Anyway, I used basically the same code and it's returning this:

Cross-Page Tests
    1) requesting to buy fingerstyle course from the fingerstyle page should populate the referrer field
    2) requesting a group rate from the home page should populate the referrer field
    ✓ visiting the "buy fingerstyle course" page directly should result in an empty referrer field (379ms)

The funny part is that the 3rd test is actually working. So the zombie js headless browser is doing its job. But something is happen when it needs to click in the link with class "buy" I created. For instance, this is the code for the first test:

`test('requesting to buy fingerstyle course from the fingerstyle page should populate the referrer field', function(done){

    let referrer = 'http://localhost:3000/courses/fingerstyle';
    browser.visit(referrer, function(){
        browser.clickLink('.buy', function(){
            assert(browser.field('referrer').value === referrer);
            done();
        });
    });
});`

The code at the form is exactally like the one in the book. 

Thank you in advance.

**Comment by EthanRBrown** [comment]
Hm, @wvict , I'm not sure I understand the problem you're describing...is the test you list failing when it should succeed, or succeeding when it should fail?

By the way, the next edition of the book won't have the Zombie-based tests...they just caused too many problems.  However, I can wholeheartedly recommend [Cypress](https://www.cypress.io/) for testing these days...they've really done a great job making it easy to write browser-based integration tests, and it's what I'm using for all my web applications now.

**Comment by w3slley** [comment]
@EthanRBrown The three tests were supposed to succeed. The value of the document. referrer is present in the hidden input and I checked while going into the page myself (from both pages I wanted to test). Anyway, I'll take a look on Cypress and see how things work. It's actually my first contact with testing and I know something went wrong because I deviated from the book's example. But I think that's how you learn things: you break them up and try to put them back together, and the harder you want to hit your head against the wall the better haha. @EthanRBrown Any advice for someone who's already knowledgeable of the LAMP stack and is starting to learn NodeJs?

Thank you for the answer.
