### ISSUE TITLE
Views Folder

### ISSUE THREAD

**Issue by pietrofxq** [EthanRBrown/web-development-with-node-and-express#35]
I'm wondering how doing that:

```javascript
app.get('/about', function(req, res) {
 res.render('about')
})
```
Can render the file views/about.html. I didn't specify anywhere where my views folder is. Taking a look on the source of ```express-handlebars.js``` I can see that the file set two pathnames, one for the 'layouts' and other for 'partials'. But I don't see anywhere a reference to views/. From where this is coming from?

**Comment by EthanRBrown** [comment]
Good question; I had to do a little digging to find the answer.  As it turns out, the choice of `views` folder is not a function of `express-handlebars`, but of `express` itself.  `express-handlebars` sets the layouts and partials directories explicitly because those are extensions to the Express view engine.  The location of the view directory is configured by Express itself.  See line 114 here: https://github.com/strongloop/express/blob/4.13.1/lib/application.js
