### ISSUE TITLE
req.user.name is undefined

### ISSUE THREAD

**Issue by pietrofxq** [EthanRBrown/web-development-with-node-and-express#37]
I'm following the Chapter 18, 'Security'. I was able to get the login working with no problems, but I can't access the user information through `req.user`.

I googled the problem and everyone said that the problem is that `express-session` isn't correctly enabled, but I'm using sessions in the app (like the flash thing) and the setup is equal to the project files:

``` javascript
app.use(bodyParser.urlencoded({extended: true}))
app.use(bodyParser.json())

var MongoSessionStore = require('session-mongoose')(require('connect'))
var sessionStore = new MongoSessionStore({
    url: credentials.mongo[app.get('env')].connectionString
})

app.use(require('cookie-parser')(credentials.cookieSecret));
app.use(require('express-session')({
    store: sessionStore,
    resave: false,
    saveUninitialized: false,
    secret: credentials.cookieSecret,
}));
```

**Comment by EthanRBrown** [comment]
Can you do `console.log(req.user)` and see if `req.user` is even getting set?

**Comment by pietrofxq** [comment]
It isn't.

**Comment by EthanRBrown** [comment]
Without seeing your code, there's not much more I can diagnose at this point.  The auth flow can be very tricky: there are a lot of moving parts and things have to be "just right" for OAuth to work properly (which is an unfortunate consequence of security).  I recommend you making sure the companion repo works correctly for you, then compare its code against your code.  I just validated that `req.user` is getting set in the repo code by doing a `console.log` on the `/account` route:

```javascript
app.get('/account', allow('customer,employee'), function(req, res){
    console.log('>>>> user:');
    console.log(req.user);
    console.log('<<<<');
    res.render('account', { username: req.user.name });
});
```

The steps you'll need to go through (a brief summary of what's in the book):

1) Set up an app on Facebook or Google.  Set "localhost:3000" as the domain and valid callback URL.
2) Make sure the Facebook or Google auth tokens are set correctly in `credentials.js`.
3) Spin up the server (`node meadowlark.js`)
4) Try to authorize (`localhost:3000/auth/facebook` or `localhost:3000/auth/google`)
5) If successful, you'll be redirected to `localhost:3000/account`, and see the welcome message.
6) Add the `console.log` shown above to verify that `req.user` is getting set.

If all that works (and it should, because I just double-checked to make sure the repo is working correctly), you can start analyzing the difference between your code and the repo code.

**Comment by pietrofxq** [comment]
Ok - after some digging I found the issue.

My route to ```/account``` was inside ```routes.js``` among the other routes.

By removing this route definition from there and pasting after ```auth.registerRoutes()``` in ```meadowlark.js```, the ```req.user``` property got populated.

There's any explanation for that? I'm enjoying node so far, but these kind of things really bother me.

**Comment by EthanRBrown** [comment]
Hm... @pietrofxq , I think the important thing was that you moved it after `auth.init()`...`auth.registerRoutes()`.  If you look in _lib/auth.js_, you'll see that the `init` method adds Passport middleware to the Express app:

```javascript
app.use(passport.initialize())
app.use(passport.session())
```

One of these middleware (I'm guessing `initialize`, without digging into the code) sets `req.user`.

Remember that the _order that Express middleware is added is important_.  The way Express works is that for every request, it'll process middleware (which includes route definitions) _in the order in which it was added to the app_ until it finds a matching one.  So if it matches your route before processing the Passport middleware that provides the `req.user` property, you won't see it!
