### ISSUE TITLE
Location of unit test

### ISSUE THREAD

**Issue by reybango** [EthanRBrown/web-development-with-node-and-express#84]
Hey @EthanRBrown, curious why you setup tests-unit.js in /qa instead of /public/qa. Didn't seem to mention anything in the book.

**Comment by metalsh33p** [comment]
I'm guessing one reason is because the tests in /qa and /public/qa are executed differently. tests-unit.js is run from the command line while those in /public/qa are handled in the browser. 

This distinction in folders is important when you go to automate testing with Grunt. You would have to be much more specific in your grunt config as to which tests it should automate if you lumped all the tests into one folder, because not all of them are run from the command line. Having a separate /qa folder allows you to put something like `src: 'qa/tests-*.js' ` in your grunt config and then you wouldn't have to worry about updating the config when you add a new test.

Maybe a lesser reason- separate folders also prevent users from learning more about the workings of your site if for some reason they successfully hit your page testing (they shouldn't), as /qa wouldn't be accessible to them.

**Comment by EthanRBrown** [comment]
Yes, @metalsh33p is correct.  `test-unit.js` are unit tests designed to be run on the back end, and therefore don't belong in `public`.  If there were unit tests for front-end code, it's conceivable that the code should go in `public`, but browser-side testing is more difficult to automate.  I'll be making pretty significant changes to the way testing is approached in the next edition of the book.
